### PR TITLE
accept single value return in CancelByOrderId()

### LINKED ISSUE #45: CancelByOrderId exception
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| NuGet Package            |      4.1.2           |
| .NET Core?                   |        .net 5         |
| .NET Full Framework?   |                 |
| Windows OS?              |      10 -1909 18363.1440            |
| Linux OS?                    |                  |
| Visual Studio?              |         2019         |

### What is the expected behavior?
Method CancelOrderById should return the id of the order canceled

### What is the actual behavior?
Exception parsing the JSON response. The method appears to be expecting a List<Guid> to be returned but it's instead getting a single Id

### Any possible solutions?
Switch the method to return Guid instead of List<Guid> and change the JSON deserialization to match

### How do you reproduce the issue?
Try to cancel an order by id

### Can you identify the location in the source code where the problem exists?
CoinBaseProClient.Orders CancelOrderById

### If the bug is confirmed, would you be willing to submit a PR?

Yes / No _(Help can be provided if you need assistance submitting a PR)_

### PR DESCRIPTION
**Pull request by vslee**
- added SingleOrArrayConverter to be able to accept both a single value alone, as well as a single value array
- incorporated in CancelOrderById()
- added additional test
- fixes #45

### CODE REVIEW

**Comment by vslee** [comment]
@bchavez any thoughts?

**Comment by bchavez** [comment]
@vslee I haven't had time to look at the issue. Currently, I have a few life events that are consuming a lot of my free time at the moment. I hope to get back to work in open-source in a few months.

**Comment by bchavez** [comment]
What could help immensely is showing some fiddler traces that show the problem at an HTTP request/response network level. See this page here: https://github.com/bchavez/Coinbase/wiki/Debugging-with-Fiddler

**Comment by vslee** [comment]
@bchavez Sorry to hear that. I hope everything works out for you.

As requested, here are the Fiddler traces for both PRs.
Screenshot delete coinbase pro order fiddler

**Comment by vslee** [comment]
@bchavez anything else I can provide?

**Comment by bchavez** [comment]
Released v4.2.2 with the fix. Thank you.
* https://www.nuget.org/packages/Coinbase.Pro/4.2.2

**Pull request closed without merging**
