### PR TITLE
Make code snippets compile

### PR DESCRIPTION
**Pull request by SimonCropp**
I couldn't resist the urge to make your snippets in the readme be compilable https://github.com/SimonCropp/MarkdownSnippets

note that it found one snippet that would not compile `new CoinbaseProWebsocket` should be `new CoinbaseProWebSocket`

### CODE REVIEW

**Comment by bchavez** [comment]
Hey, thanks @SimonCropp! That's pretty cool. Really nice tool! I can see already, great to keep docs current!

I tried to check out your PR and compile everything but seems my machine gets stuck rebuilding the `Coinbase.Tests` project with the changes applied in this PR:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "MarkdownSnippets.DocoTask" task failed unexpectedly.
System.IO.IOException: The process cannot access the file 'C:\Code\Projects\Public\Coinbase.Pro\Source\_ReSharper.Caches\ReSharperPlatformVs16203_2a8eeedb.Coinbase.Pro.00\Db\000915.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at MarkdownSnippets.FileSnippetExtractor.Read(String path, Int32 maxWidth, String newLine) in C:\projects\markdownsnippets\src\MarkdownSnippets\Reading\FileSnippetExtractor.cs:line 102
   at MarkdownSnippets.FileSnippetExtractor.<>c__DisplayClass7_0.<Read>b__1(String path) in C:\projects\markdownsnippets\src\MarkdownSnippets\Reading\FileSnippetExtractor.cs:line 83
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MarkdownSnippets.DirectoryMarkdownProcessor.AddSnippetsFrom(String directory) in C:\projects\markdownsnippets\src\MarkdownSnippets\Processing\DirectoryMarkdownProcessor.cs:line 187
   at MarkdownSnippets.DirectoryMarkdownProcessor..ctor(String targetDirectory, AppendSnippetsToMarkdown appendSnippets, DocumentConvention convention, Boolean scanForMdFiles, Boolean scanForSnippets, Boolean scanForIncludes, Action`1 log, Nullable`1 writeHeader, String header, DirectoryFilter directoryFilter, Nullable`1 readOnly, Int32 tocLevel, IEnumerable`1 tocExcludes, IEnumerable`1 documentExtensions, Boolean treatMissingAsWarning, Int32 maxWidth, Boolean validateContent, String newLine) in C:\projects\markdownsnippets\src\MarkdownSnippets\Processing\DirectoryMarkdownProcessor.cs:line 120
   at MarkdownSnippets.DirectoryMarkdownProcessor..ctor(String targetDirectory, DocumentConvention convention, Boolean scanForMdFiles, Boolean scanForSnippets, Boolean scanForIncludes, Action`1 log, Nullable`1 writeHeader, String header, DirectoryFilter directoryFilter, Nullable`1 readOnly, LinkFormat linkFormat, Int32 tocLevel, IEnumerable`1 tocExcludes, IEnumerable`1 documentExtensions, Boolean treatMissingAsWarning, Int32 maxWidth, String urlPrefix, Boolean validateContent, String newLine, Boolean hashSnippetAnchors) in C:\projects\markdownsnippets\src\MarkdownSnippets\Processing\DirectoryMarkdownProcessor.cs:line 53
   at MarkdownSnippets.DocoTask.Execute() in C:\projects\markdownsnippets\src\MarkdownSnippets.MsBuild\DocoTask.cs:line 60
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Coinbase.Tests	C:\Users\USER_NAME\.nuget\packages\markdownsnippets.msbuild\21.7.1\build\MarkdownSnippets.MsBuild.targets	18	
```
image

Is it intentional?

**Comment by SimonCropp** [comment]
nope. not intended. dont merge and i will debug it

**Comment by SimonCropp** [comment]
can u try now?

**Comment by bchavez** [comment]
Hi Simon,

I'm not blocked from building the test project anymore; thank you!

I have a few more questions about `MarkdownSnippets`; I did notice a somewhat noticeable increase in build time for the Test project. Somewhere between 9 - 6 seconds extra when the `PackageReference` is added.

* Do you know what that might be?
* I kinda get the feeling `MarkdownSnippets` is doing some kind of large directory recursive traversal; which could be adding to some major delay. Is it possible to limit the scope via some MSBuild properties?

#### Enabled `PackageReference Include="MarkdownSnippets.MsBuild" Version="21.7.2"`
```
dotnet build in Source\Coinbase.Tests
Time Elapsed 00:00:11.48
Time Elapsed 00:00:08.03
Time Elapsed 00:00:07.47
Time Elapsed 00:00:07.47
Time Elapsed 00:00:07.43
```
#### Commeted/Disabled `PackageReference Include="MarkdownSnippets.MsBuild" Version="21.7.2"`
```
dotnet build in Source\Coinbase.Tests
Time Elapsed 00:00:02.62
Time Elapsed 00:00:01.53
Time Elapsed 00:00:01.49
Time Elapsed 00:00:01.69
Time Elapsed 00:00:01.49
```

**Comment by SimonCropp** [comment]
agreed, thats not acceptable. i will look into it

**Comment by bchavez** [comment]
Just for an extra data point: I deleted `\Source\packages` folder and ran `dotnet build` in `Coinbase.Tests` and found build times are back to normal.

### With PackageReference enabled:
```
Time Elapsed 00:00:01.78
Time Elapsed 00:00:01.51
Time Elapsed 00:00:01.41
Time Elapsed 00:00:01.51
```

So, I think maybe it is related to directory recursion that increases the build time. The bigger the file system structure, the longer build times will increase.

**Comment by bchavez** [comment]
One way to introduce some delay is by executing the following:

```
C:\Code\Projects\Public\Coinbase.Pro\Source>dotnet restore --packages packages Coinbase.Tests
```

```
C:\Code\Projects\Public\Coinbase.Pro\Source\Coinbase.Tests>dotnet build
Time Elapsed 00:00:05.01
Time Elapsed 00:00:02.94
Time Elapsed 00:00:02.57
```
Delete the `\Source\packages` folder:

image

Then run:
```
C:\Code\Projects\Public\Coinbase.Pro\Source\Coinbase.Tests>dotnet build
Time Elapsed 00:00:01.48
Time Elapsed 00:00:01.48
Time Elapsed 00:00:01.48
```
And build times come back down again.

I think previously, I had bout 13,000 files in `\Source\packages` (probably from .net core 1.1 days, that I never deleted)

**Comment by bchavez** [comment]
Ah, here we go, Simon! Here's a reliable repro:

```
C:\Code\Projects\Public\Coinbase.Pro\Source>dotnet restore --packages packages Coinbase.Tests
C:\Code\Projects\Public\Coinbase.Pro\Source>dotnet restore --packages packages2 Coinbase.Tests
C:\Code\Projects\Public\Coinbase.Pro\Source>dotnet restore --packages packages3 Coinbase.Tests
C:\Code\Projects\Public\Coinbase.Pro\Source>dotnet restore --packages packages4 Coinbase.Tests
C:\Code\Projects\Public\Coinbase.Pro\Source>dotnet restore --packages packages5 Coinbase.Tests
C:\Code\Projects\Public\Coinbase.Pro\Source>dotnet restore --packages packages6 Coinbase.Tests
C:\Code\Projects\Public\Coinbase.Pro\Source>dotnet restore --packages packages7 Coinbase.Tests
```
image

And back up to 10s build times in `Coinbase.Tests` folder:

```
C:\Code\Projects\Public\Coinbase.Pro\Source\Coinbase.Tests>dotnet build
Time Elapsed 00:00:10.86
Time Elapsed 00:00:10.73
Time Elapsed 00:00:10.41
```

**Comment by SimonCropp** [comment]
can u try now?

**Comment by SimonCropp** [comment]
note i now handle `packages` OOTB. if u want to exclude others use `Exclude` in the config file
https://github.com/SimonCropp/MarkdownSnippets/blob/master/docs/config-file.md#all-settings

**Comment by bchavez** [comment]
Soo much better! Thank you so much @SimonCropp! Going to merge this.

Do you think it would be worthwhile to have something in the settings file that is "exclude by default" and "only process these files":

```
{
  "Updates":[
      {target: "..\..\README.md, source: "Coinbase.Tests\Snippets\*"}
    ]
}
```

**Pull request merged**
