### PR TITLE
Withdrawals time data type fix

### PR DESCRIPTION
**Pull request by la4atld**
Hi, 

1) UnixSeconds:
FlurlHttpException: Call failed with status code 400 (Bad Request): GET https://api.pro.coinbase.com/transfers?type=withdraw&before=1596523347&after=1596534147

2) UnixMilliseconds:
FlurlHttpException: Call failed with status code 400 (Bad Request): GET https://api.pro.coinbase.com/transfers?type=withdraw&before=1596523404854&after=1596534204854

3) DateTime:
https://api.pro.coinbase.com/transfers?type=withdraw&before=2020-08-04T07%3A33%3A39.9712895&after=2020-08-04T10%3A33%3A39.971289 - works (?)

### CODE REVIEW

**Comment by bchavez** [comment]
Hi @la4atld. I don't think this is how pagination in the **Coinbase Pro** API works. The `Before` and `After` is not based on unix time seconds. 

Please read more here:
* https://docs.pro.coinbase.com/#pagination
* https://github.com/bchavez/Coinbase.Pro#pagination

`Before` and `After` are **page IDs**; **not** unix seconds. Please update to the latest version here: https://www.nuget.org/packages/Coinbase.Pro/3.0.3

Let me know how it goes.

Thanks,
Brian

**Comment by la4atld** [comment]
Hi @bchavez,
I understand where you're coming from. 
In the "/transfers" description it says "See the Pagination section for retrieving additional entries after the first page." which I think is misleading.
If you take a closer look you'll see that every request that supports pagination says so explicitly with "This request is paginated." notice. And by the looks of it pagination only applies to /trades, /fills and /orders.
I've tested seconds, ms, pages (see below) and DateTime and am quite sure only DateTime params work.

FlurlHttpException: Call failed with status code 400 (Bad Request): GET https://api.pro.coinbase.com/transfers?type=withdraw&limit=10&before=2
FlurlHttpException: Call failed with status code 400 (Bad Request): GET https://api.pro.coinbase.com/transfers?type=withdraw&limit=10&after=2

Thanks for looking into this.

**Comment by bchavez** [comment]
Hi @la4atld, thanks for the comment. I did a quick integration test and I think you might be correct. The normal pagination with Coinbase Pro API seems different for withdrawals. LOL. :rofl: I will do more investigation after work tomorrow.

**Comment by bchavez** [comment]
Hi @la4atld, I was able to confirm the behavior of the absolute weirdness with their APIs and inconsistency. The `List Withdrawals` methods now take `DateTimeOffset` as parameters.

Please give the latest changes a try here: https://www.nuget.org/packages/Coinbase.Pro/3.0.4

Thanks,
Brian

**Comment by la4atld** [comment]
Hi @bchavez,
I can confirm it's working as expected, thank you for sorting this! 👍

**Pull request closed without merging**
