### PR TITLE
Added Fee Estimate

### PR DESCRIPTION
**Pull request by la4atld**
Added Fee Estimate
Added destination tag/network fee to crypto address withdrawal

### CODE REVIEW

**Review by bchavez — APPROVED** [review]
Great work @la4atld! Thank you for the PR. My apologies for the delay. I should be able to get a new release out this weekend.

**Comment by la4atld** [comment]
@bchavez Thank you mate

**Comment by bchavez** [comment]
New version published: https://www.nuget.org/packages/Coinbase.Pro/3.3.0

Let me know how it goes!

**Comment by la4atld** [comment]
Works great as expected, thank you!

________________________________

**Pull request merged**
