### PR TITLE
Fix FlurlParsingException when retrieving fills.

### PR DESCRIPTION
**Pull request by lucaswalter**
Updated the Fills.UsdVolume property to be nullable to handle a FulrlParsingException:

image

Sentry Link: https://sentry.io/share/issue/d07d6651bd744232b07717ee358f8984/

### CODE REVIEW

**Comment by bchavez** [comment]
Hi Lucas,

Thanks for the PR. Any chance we can get a sample JSON with the null field that caused the exception?

I'd like to write an accompanying unit test [in here](https://github.com/bchavez/Coinbase.Pro/blob/master/Source/Coinbase.Tests/EndpointTests/OrdersTest.cs) to cover this. I know it seems a little mundane to test for nullability; but the more verity of unit tests we have the better.

Thanks,
Brian

**Comment by lucaswalter** [comment]
Hi Brian, I would be happy to provide that. What approach to you recommend for getting the sample json? Currently trying to recreate this request in postman, but am not sure if there is an easier method.

Thanks!

**Comment by bchavez** [comment]
Hi Lucas,

Thanks for getting some sample JSON we can test. I really appreciate your help with that.

Here's how I debug my clients:

1. Install [Fiddler](https://www.telerik.com/fiddler); "download telerik fiddler" is way at the bottom:
chrome_2971

1. Next, in Fiddler, `Tools > Options ...`. Tick the following options to enable decryption HTTPS traffic.
Fiddler_2972
  You'll probably get some dialog boxes that pop ups warning you about installing a "trusted root certificate". Click the affirmative to install the debugging root certificate.

1. In the `Connections` tab, tell Fiddler to listen for connections on 8888.
Fiddler_2965

1. Next, tell **Flurl** to use the Fiddler proxy you have setup:

```csharp
async Task Main()
{
   var c = new CoinbaseProClient();
   c.EnableFiddlerDebugProxy("http://localhost.:8888");
   //Take special note of the prefix "." here in "localhost." name above
   
   var prod = await c.MarketData.GetProductsAsync();
   
   prod.Dump();
}

// Define other methods and classes here
public static class DebuggingExtensions
{
   public static CoinbaseProClient EnableFiddlerDebugProxy(this CoinbaseProClient client, string proxyUrl)
   {
      var webProxy = new WebProxy(proxyUrl, BypassOnLocal: false);

      client.Configure(cf => {
         cf.HttpClientFactory = new DebugProxyFactory(webProxy);
      });
         
      return client;
   }

   private class DebugProxyFactory : DefaultHttpClientFactory
   {
      private readonly WebProxy proxy;

      public DebugProxyFactory(WebProxy proxy)
      {
         this.proxy = proxy;
      }

      public override HttpMessageHandler CreateMessageHandler()
      {
         return new HttpClientHandler
         {
            Proxy = this.proxy,
            UseProxy = true
         };
      }
   }
}
```

5. And voila, debugged HTTPS traffic:

Fiddler_2973

I hope this works for ya. Also, the "Raw" response inspector tab instead of JSON structured view can probably help too if you just want to copy/paste the whole JSON body.

Please let me know if you need help!

Thanks,
Brian

**Comment by lucaswalter** [comment]
Thanks for the instructions! Here's a snipped that had null:

`{  
      "created_at":"2017-11-07T00:23:07.425Z",
      "trade_id":1791448,
      "product_id":"ETH-BTC",
      "order_id":"1bac19dd-ba2f-4cb4-becd-dee24c4a3ca4",
      "user_id":"56d911bd56816d6e7a0001d0",
      "profile_id":"53b7df50-1c5c-4b76-a730-db9bd2f608a8",
      "liquidity":"M",
      "price":"0.04232000",
      "size":"8.00000000",
      "fee":"0.0000000000000000",
      "side":"buy",
      "settled":true,
      "usd_volume":null
   }`

**Comment by lucaswalter** [comment]
Here is the full json too: https://ufile.io/8n6nrfpy

**Comment by bchavez** [comment]
Excellent work Lucas! Thanks for getting that JSON, give me a few minutes to setup a unit test for this case and we'll be good to go with a new release soon!

**Comment by lucaswalter** [comment]
Happy to help! Thank you for such a quick response! :)

**Comment by bchavez** [comment]
Hey Lucas,

v2.0.6 is now up with your changes. https://www.nuget.org/packages/Coinbase.Pro/2.0.6

**Comment by lucaswalter** [comment]
Thank you very much!

**Pull request merged**
